In [2]:
from manim import*
from manim.utils.color import Colors

Manim Community v0.16.0.post0

In [4]:
%%manim -v WARNING Time

import numpy as np
import math

class Time(MovingCameraScene):
    
    def construct(self):
        
        def there_and_back2(t):
            new_t = 2 * t if t < 0.5 else 2 * (1 - t)
            return new_t
        
        def y_coord_given_tracker(tracker):
            mod = tracker%2
            new_t = mod if mod < 1 else((2-mod))
            return new_t*4 -2
        def moving_clock():
            tracker = ValueTracker(0)
            rect = always_redraw(lambda:Rectangle(width=2.0, height=4.0).shift(LEFT*3).shift( RIGHT*(tracker.get_value())*3 ))
            dot = always_redraw(lambda:  Dot([rect.get_center()[0],   y_coord_given_tracker(tracker.get_value())   ,0]))
            
            time = always_redraw(lambda:  Text(str(round(tracker.get_value(),2))).next_to(rect))

            path = TracedPath(lambda :dot.get_center(), dissipating_time=6, stroke_opacity=[1, 1])
            self.add(always_redraw(lambda: VGroup(rect,dot, path, time)))
            self.play(tracker.animate(run_time=2 ,rate_func = linear).set_value(2))
        
        def clock(shift=None):
            tracker = ValueTracker(0)
            
            rect = always_redraw(lambda:Rectangle(width=2.0, height=4.0).shift(shift if shift[0] else LEFT*0) )
            
            dot = always_redraw(lambda:  Dot([rect.get_center()[0], y_coord_given_tracker(tracker.get_value())   ,0]))
            
            time = always_redraw(lambda:  Text(str(round(tracker.get_value(),2))).next_to(rect).set_color_by_gradient(RED,YELLOW))
            
            path = TracedPath(lambda :dot.get_center(), dissipating_time=0.3, stroke_opacity=[1, 1])
            
            brace = BraceLabel(rect, "d", LEFT)

            self.play(Create(always_redraw(lambda: VGroup(rect,dot, path))), FadeIn(time), run_time = 2)
            self.add(brace)
            self.play(tracker.animate(run_time=2*8 ,rate_func = linear).set_value(2*8))
        #time dialated w paths
        def both1(shift=None):
            tracker = ValueTracker(0)
            
            rect = always_redraw(lambda:Rectangle(width=2.0, height=4.0).shift(shift if shift[0] else LEFT*0) )
            
            dot = always_redraw(lambda:  Dot([rect.get_center()[0], y_coord_given_tracker(tracker.get_value())   ,0]))
            
            time = always_redraw(lambda:  Text(str(round(tracker.get_value(),2))).set_color_by_gradient(RED,YELLOW).next_to(rect))
            
            path = TracedPath(lambda :dot.get_center(), dissipating_time=2, stroke_opacity=[1, 1])
            
            group = always_redraw(lambda: VGroup(rect,dot, path, time))
            self.add(group)
            
            rect1 = always_redraw(lambda:Rectangle(width=2.0, height=4.0).shift(LEFT*4).shift( RIGHT*(tracker.get_value()*(2**(1/2)/2))*4 ))
            dot1 = always_redraw(lambda:  Dot([rect1.get_center()[0],   y_coord_given_tracker(tracker.get_value()*(2**(1/2)/2))   ,0]))
            
            time1 = always_redraw(lambda:  Text(str(round(tracker.get_value()*(2**(1/2)/2),2))).set_color_by_gradient(RED,YELLOW).next_to(rect1))

            path1 = TracedPath(lambda :dot1.get_center(), dissipating_time=8, stroke_opacity=[1, 1])
            rp1 = TracedPath(lambda :np.subtract(rect1.get_vertices()[1],[0,0.05,0]), dissipating_time=0.5, stroke_opacity=[1, 0], stroke_width = 15)
            rp2 = TracedPath(lambda :np.subtract(rect1.get_vertices()[2],[0,-0.05,0]), dissipating_time=0.5, stroke_opacity=[1, 0], stroke_width = 15)

            print(rect1.get_vertices())
            tri = always_redraw(lambda: Polygon(   rect1.get_vertices()[0] ,rect1.get_vertices()[3], [rect1.get_vertices()[0][0]+2,0,0]   ))
            self.add (rect1,dot1, path1, time1,tri, rp1, rp2)
            
            # def follow_camera(camera):
            #     camera.move_to(rect1.get_center())
            # self.camera.frame.add_updater(follow_camera)
            # self.play(self.camera.frame.animate.scale(0.65))
            self.play(tracker.animate(run_time=8 ,rate_func = linear).set_value(2*2))
        #time same no paths
        def both2(shift=None):
            tracker = ValueTracker(0)
            
            rect = always_redraw(lambda:Rectangle(width=2.0, height=4.0).shift(shift if shift[0] else LEFT*0) )
            
            dot = always_redraw(lambda:  Dot([rect.get_center()[0], y_coord_given_tracker(tracker.get_value())   ,0]))
            
            time = always_redraw(lambda:  Text(str(round(tracker.get_value(),2))).set_color_by_gradient(RED,YELLOW).next_to(rect))
            
            path = TracedPath(lambda :dot.get_center(), dissipating_time=0.3, stroke_opacity=[1, 1])
            
            group = VGroup(rect,dot, time)
        
            self.play(FadeIn(group))
            self.add(path)
            rect1 = always_redraw(lambda:Rectangle(width=2.0, height=4.0).shift(LEFT*4).shift( RIGHT*(tracker.get_value())*4 ))
            dot1 = always_redraw(lambda:  Dot([rect1.get_center()[0],   y_coord_given_tracker(tracker.get_value())   ,0]))
            
            time1 = always_redraw(lambda:  Text(str(round(tracker.get_value(),2))).set_color_by_gradient(RED,YELLOW).next_to(rect1))

            path1 = TracedPath(lambda :dot1.get_center(), dissipating_time=8, stroke_opacity=[1, 1])
            rp1 = TracedPath(lambda :np.subtract(rect1.get_vertices()[1],[0,0.05,0]), dissipating_time=0.5, stroke_opacity=[1, 0], stroke_width = 15)
            rp2 = TracedPath(lambda :np.subtract(rect1.get_vertices()[2],[0,-0.05,0]), dissipating_time=0.5, stroke_opacity=[1, 0], stroke_width = 15)

            print(rect1.get_vertices())
            tri = always_redraw(lambda: Polygon(   rect1.get_vertices()[0] ,rect1.get_vertices()[3], [rect1.get_vertices()[0][0]+2,0,0]   ))
            
            self.play (FadeIn(VGroup(rect1,dot1, time1,tri)))
            self.add(rp1, rp2, path1)
            
#             def follow_camera(camera):
#                 camera.move_to(rect1.get_center())
#             def scale_cam(camera):
#                 self.camera.frame.set_width(Group(rect, rect1).get_width()*2)
#                 self.camera.frame.move_to(rect1.get_center())
           
#             self.camera.frame.add_updater(scale_cam)
#             self.play(self.camera.frame.animate.scale(Group(rect, rect1).get_width()*2).move_to(rect1.get_center()))
            
            self.play(tracker.animate(run_time=8*2 ,rate_func = linear).set_value(4*2))
        
        #time same draws tiangle and solves for delta t  
        def both3(shift=None):
            tracker = ValueTracker(0)
            
            rect = always_redraw(lambda:Rectangle(width=2.0, height=4.0).shift(shift if shift[0] else LEFT*0) )
            
            dot = always_redraw(lambda:  Dot([rect.get_center()[0], y_coord_given_tracker(tracker.get_value())   ,0]))
            
            time = always_redraw(lambda:  Text(str(round(tracker.get_value()/2,2))).set_color_by_gradient(RED,YELLOW).next_to(rect))
            
            path = TracedPath(lambda :dot.get_center(), dissipating_time=0.3, stroke_opacity=[1, 1])
            
            clock1 = always_redraw(lambda: VGroup(rect,dot, path, time))
            self.add(clock1)
            
            rect1 = always_redraw(lambda:Rectangle(width=2.0, height=4.0).shift(LEFT*4).shift( RIGHT*(tracker.get_value())*4 ))
            dot1 = always_redraw(lambda:  Dot([rect1.get_center()[0],   y_coord_given_tracker(tracker.get_value())   ,0]))
            time1 = always_redraw(lambda:  Text(str(round(tracker.get_value()/2,2))).set_color_by_gradient(RED,YELLOW).next_to(rect1))
            path1 = TracedPath(lambda :dot1.get_center(), dissipating_time=8, stroke_opacity=[1, 1])
            rp1 = TracedPath(lambda :np.subtract(rect1.get_vertices()[1],[0,0.05,0]), dissipating_time=0.5, stroke_opacity=[1, 0], stroke_width = 15)
            rp2 = TracedPath(lambda :np.subtract(rect1.get_vertices()[2],[0,-0.05,0]), dissipating_time=0.5, stroke_opacity=[1, 0], stroke_width = 15)
            tri = always_redraw(lambda: Polygon(   rect1.get_vertices()[0] ,rect1.get_vertices()[3], [rect1.get_vertices()[0][0]+2,0,0]   ))
            
            clock2 = VGroup(rect1,dot1, path1 ,time1,tri, rp1, rp2)
            self.add (clock2)
            
            # def follow_camera(camera):
            #     camera.move_to(rect1.get_center())
            # self.camera.frame.add_updater(follow_camera)
            # self.play(self.camera.frame.animate.scale(0.65))
            self.play(tracker.animate(run_time=2 ,rate_func = linear).set_value(1))
            # self.wait(3)
            self.play(FadeOut(clock1,clock2[3]))
        # def tri_brace():
            right = Polygon([0,2,0],[0,-2,0], [-4,-2,0], stroke_width = 8).set_color_by_gradient(RED,YELLOW)
            hyp = BraceLabel(right, "\Delta t * C", [-1,1,0])
            legA= BraceLabel(right, "d", RIGHT)
            legB= BraceLabel(right, "\Delta t * V" )
            braces = VGroup(legA,legB, hyp)
            self.play(DrawBorderThenFill(right))
            self.play(DrawBorderThenFill(braces), run_time = 2 )
            # self.wait(1)
            # for brace in braces:
            #     self.play(Wiggle(brace))
            #     self.wait(0.2)
            self.play(FadeOut(clock2[0],clock2[1],clock2[2],clock2[4],clock2[5],clock2[6]))

            self.play(Group(braces, right).animate.shift(LEFT*2))
            eq = MathTex("(d)^{2}","+( \Delta t * C)^{2}","= (\Delta t * V)^{2}").arrange_submobjects().shift(UP*3, RIGHT*3)
            # self.add(eq)
            for i, brace in enumerate(braces):
                self.play(ReplacementTransform(brace.copy(), eq[i]))
                self.wait(0.2)
            eq2 = MathTex("(d)^{2}","= (\Delta t * V)^{2}", "-","( \Delta t * C)^{2}").arrange_submobjects().shift(UP*2, RIGHT*3)
            self.play(TransformMatchingTex(eq.copy(),eq2))
            eq3 = MathTex("(d)^{2}","="," (\Delta t)^{2}"," * V^{2}", "+","( \Delta t)^{2} ","* C^{2}").arrange_submobjects().shift(UP*1, RIGHT*3)
            self.play(TransformMatchingTex(eq2.copy(),eq3))
            eq4 = MathTex("(d)^{2}","= ( \Delta t)^{2}","(V^{2}", "+C^{2})").arrange_submobjects().shift( RIGHT*3)
            self.play(TransformMatchingTex(eq3.copy(),eq4))
            eq5 = Group(MathTex("(d)^{2}"," \over V^{2}+C^{2}"), MathTex("=  \Delta t^{2}")).arrange_submobjects().shift(DOWN, RIGHT*3)
            self.play(TransformMatchingTex(eq4.copy(),eq5))
            eq6 = Group(MathTex("\sqrt{","(d)^{2}"," \over V^{2}+C^{2}}"," =\Delta t")).arrange_submobjects().shift(DOWN*2.5, RIGHT*3)
            self.play(TransformMatchingTex(eq5.copy(),eq6))
            
            eqs1 = Group(eq,eq2,eq3,eq4,eq5,eq6)
            self.play(FadeOut(right, braces))
            self.play(eqs1.animate.shift(LEFT*6))
            
            # eq7 = MathTex("\sqrt{","(d)^{2}","\over {","V^{2}","  {(","V^{2}+C^{2})}\over {","V^{2}}  }} ","=\Delta t").arrange_submobjects().shift(UP*3, RIGHT*3)
            eq7 = MathTex("\sqrt{(d)^{2}\over {C^{2}  {(V^{2}+C^{2})}\over {C^{2}}  }} =\Delta t").arrange_submobjects().shift(UP*3, RIGHT*3)
            self.play(Transform(eq6.copy(),eq7))
            eq8 = MathTex("\sqrt{ (d) ^{ 2 } \over { C^ {2 } ( { { { V^2 } \over { C^2 } } + 1 ) } } } =\Delta t").arrange_submobjects().shift(UP*1, RIGHT*3)
            self.play(Transform(eq7.copy(),eq8))
            eq9 = MathTex("{ d \over { C    \sqrt  { 1+   { ( { { V } \over { C} } ) }^2  }    }  }","","=\Delta t").arrange_submobjects().shift(DOWN, RIGHT*3)
            self.play(Transform(eq8.copy(),eq9))
            eq10 = MathTex(" {d \over C}","  *{  1\over   \sqrt  { 1+   { ({ { V } \over { C} }) }^2  }    }  ","=\Delta t").arrange_submobjects().shift(DOWN*3, RIGHT*3)
            eq9c = eq9.copy()
            self.play(Transform(eq9c,eq10))
            eq11 = MathTex("{\Delta t_{0}","  *{  1\over   \sqrt  { 1+   { ({ { C } \over { V} }) }^2  }    }  ","=\Delta t").arrange_submobjects().shift(DOWN*3, RIGHT*3)
            self.play(ReplacementTransform(eq9c[0],eq11[0]))
        plane = mobject.graphing.coordinate_systems.NumberPlane(x_range=(- 50.111111111111111, 50.111111111111111, 1), y_range=(- 20.0, 20.0, 1)).set_color_by_gradient(BLUE,GREEN).set_opacity(0.5)
        self.add(plane)
        both1(LEFT*6) 
        # clock(LEFT*0)        
        # tri_brace()



        


[[-3.  2.  0.]
 [-5.  2.  0.]
 [-5. -2.  0.]
 [-3. -2.  0.]]
